[preset 1]
legacy_layout=0
cpu_stats=1
cpu_temp=1
cpu_mhz=1
gpu_stats=1
gpu_temp=1
gpu_core_clock=1
gpu_mem_clock=1
vram=1
ram=1
fps=1
frametime=1
frame_timing=1

[preset 2]
legacy_layout=0
horizontal=1
hud_no_margin=1
font_size=16
cpu_stats=1
cpu_temp=1
gpu_stats=1
gpu_temp=1
ram=1
vram=1
fps=1
frametime=0
